import assert from "node:assert/strict";
import fs from "node:fs";
import type { AddressInfo } from "node:net";
import os from "node:os";
import path from "node:path";
import { after, before, test } from "node:test";
import vm from "node:vm";
import { buildProfile, type UserDirs } from "../src/games/profile.ts";
import { installRpgMakerBridge, readPlugins, removeRpgMakerBridge, rpgMakerBridgeState } from "../src/games/rpgmaker.ts";
import { createHub } from "../src/hub/create.ts";
import { fakeModel, text } from "./fake-model.ts";

// The RPG Maker bridge: installing the plugin into MV and MZ game folders (and taking it out
// exactly), and the plugin itself running against a real Telos hub, with stand-ins for the
// RPG Maker objects it uses.

const root = path.resolve(import.meta.dirname, "..");
const PLUGIN = path.join(root, "bridge-rpgmaker", "TelosBridge.js");

const PLUGINS_JS = `// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_CoreEngine","status":true,"description":"Core","parameters":{"Screen Width":"816"}},
{"name":"Community_Basic","status":false,"description":"Basic","parameters":{}}
];
`;

function fakeRpgMaker(layout: "mv" | "mz") {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "telos-rpgm-"));
  const dirs: UserDirs = { home: path.join(tmp, "home"), appData: path.join(tmp, "a"), localAppData: path.join(tmp, "l") };
  const install = path.join(tmp, "HeroQuest");
  const base = layout === "mv" ? path.join(install, "www") : install;
  fs.mkdirSync(path.join(base, "data"), { recursive: true });
  fs.mkdirSync(path.join(base, "js", "plugins"), { recursive: true });
  fs.writeFileSync(path.join(base, "data", "System.json"), JSON.stringify({ gameTitle: "Hero Quest" }));
  fs.writeFileSync(path.join(base, "js", "plugins.js"), PLUGINS_JS);
  fs.writeFileSync(path.join(base, "js", "plugins", "YEP_CoreEngine.js"), "// core");
  fs.writeFileSync(path.join(install, "Game.exe"), "");
  return { install, base, profile: buildProfile(path.join(install, "Game.exe"), dirs) };
}

test("installs into an MV game (www/) and comes out exactly, keeping the player's plugins", () => {
  const { install, base, profile } = fakeRpgMaker("mv");
  assert.equal(profile.engine, "RPG Maker MV/MZ");
  assert.deepEqual(rpgMakerBridgeState(profile, PLUGIN), { supported: true, installed: false });

  const report = installRpgMakerBridge(profile, { pluginJs: PLUGIN, port: 7788 });
  assert.equal(report.updated, false);
  assert.deepEqual(report.files, ["www/js/plugins/TelosBridge.js"]);
  assert.equal(fs.readFileSync(path.join(base, "js", "plugins", "TelosBridge.js"), "utf8"), fs.readFileSync(PLUGIN, "utf8"));
  const list = readPlugins(path.join(base, "js", "plugins.js"));
  assert.deepEqual(list.list.map((p) => p.name), ["YEP_CoreEngine", "Community_Basic", "TelosBridge"]);
  assert.equal(list.list[2].parameters.HubUrl, "ws://127.0.0.1:7788/ws/adapter");
  assert.match(list.head, /Generated by RPG Maker/);
  assert.deepEqual(rpgMakerBridgeState(profile, PLUGIN), { supported: true, installed: true });

  // Installing again (an update after the game quit, no port given) keeps one entry and the address.
  assert.equal(installRpgMakerBridge(profile, { pluginJs: PLUGIN }).updated, true);
  const again = readPlugins(path.join(base, "js", "plugins.js")).list;
  assert.equal(again.filter((p) => p.name === "TelosBridge").length, 1);
  assert.equal(again.at(-1)!.parameters.HubUrl, "ws://127.0.0.1:7788/ws/adapter");

  // The player turns on another plugin meanwhile: removal keeps that.
  const parts = readPlugins(path.join(base, "js", "plugins.js"));
  parts.list[1].status = true;
  fs.writeFileSync(path.join(base, "js", "plugins.js"), parts.head + JSON.stringify(parts.list) + parts.tail);

  assert.deepEqual(removeRpgMakerBridge(profile), { removed: 2 });
  const after = readPlugins(path.join(base, "js", "plugins.js")).list;
  assert.deepEqual(after.map((p) => [p.name, p.status]), [["YEP_CoreEngine", true], ["Community_Basic", true]]);
  assert.ok(!fs.existsSync(path.join(base, "js", "plugins", "TelosBridge.js")));
  assert.ok(fs.existsSync(path.join(base, "js", "plugins", "YEP_CoreEngine.js")));
  assert.deepEqual(fs.readdirSync(install).sort(), ["Game.exe", "www"], "no manifest or backup left behind");
  assert.deepEqual(fs.readdirSync(path.join(base, "js")).sort(), ["plugins", "plugins.js"]);
  assert.throws(() => removeRpgMakerBridge(profile), /isn't installed/);
});

test("MZ keeps js/ at the top; an outdated plugin is spotted", () => {
  const { base, profile } = fakeRpgMaker("mz");
  installRpgMakerBridge(profile, { pluginJs: PLUGIN, port: 7777 });
  assert.ok(fs.existsSync(path.join(base, "js", "plugins", "TelosBridge.js")));
  fs.writeFileSync(path.join(base, "js", "plugins", "TelosBridge.js"), "// an older bridge");
  assert.equal(rpgMakerBridgeState(profile, PLUGIN).outdated, true);
});

test("refuses a hand-edited plugin list and packed games, without writing anything", () => {
  const { install, base, profile } = fakeRpgMaker("mz");
  fs.writeFileSync(path.join(base, "js", "plugins.js"), "var $plugins = [ {name: 'NotJson'} ];");
  assert.throws(() => installRpgMakerBridge(profile, { pluginJs: PLUGIN }), /edited by hand/);
  assert.ok(!fs.existsSync(path.join(base, "js", "plugins", "TelosBridge.js")));
  assert.deepEqual(fs.readdirSync(install).sort(), ["Game.exe", "data", "js"]);

  fs.rmSync(path.join(base, "js", "plugins.js"));
  const state = rpgMakerBridgeState(profile);
  assert.equal(state.supported, false);
  assert.match(state.reason!, /packed/);
});

// ---------------------------------------------------------------- the plugin, live

let hub: Awaited<ReturnType<typeof createHub>>;
let game: Record<string, any>;

/** Just enough of RPG Maker's runtime for the bridge: the same names and methods it calls. */
function rpgMakerRuntime(hubUrl: string) {
  class Game_Actor {
    level = 5;
    hp = 100;
    mhp = 120;
    mp = 20;
    mmp = 30;
    tp = 0;
    atk = 10;
    exp = 500;
    constructor(
      private id: number,
      private actorName: string,
    ) {}
    actorId() { return this.id; }
    name() { return this.actorName; }
    currentExp() { return this.exp; }
    setHp(n: number) { this.hp = Math.max(0, Math.min(n, this.mhp)); }
    setMp(n: number) { this.mp = Math.max(0, Math.min(n, this.mmp)); }
    setTp(n: number) { this.tp = n; }
    changeLevel(l: number) { this.level = l; }
    changeExp(e: number) { this.exp = e; }
    maxLevel() { return 99; }
    addParam(id: number, v: number) {
      if (id === 0) this.mhp += v;
      if (id === 2) this.atk += v;
    }
    recoverAll() { this.hp = this.mhp; this.mp = this.mmp; }
  }
  const actors: Record<number, Game_Actor> = { 1: new Game_Actor(1, "Harold"), 2: new Game_Actor(2, "Therese"), 3: new Game_Actor(3, "Marsha") };
  class Game_Party {
    _gold = 300;
    _members = [1, 2];
    _items = new Map<object, number>();
    gold() { return this._gold; }
    maxGold() { return 99999999; }
    gainGold(n: number) { this._gold = Math.max(0, Math.min(this._gold + n, this.maxGold())); }
    members() { return this._members.map((id) => actors[id]); }
    leader() { return this.members()[0]; }
    steps() { return 1234; }
    numItems(item: object) { return this._items.get(item) ?? 0; }
    maxItems() { return 99; }
    gainItem(item: object, n: number) { this._items.set(item, Math.max(0, Math.min(this.numItems(item) + n, 99))); }
    inBattle() { return false; }
    addActor(id: number) { if (!this._members.includes(id)) this._members.push(id); }
    removeActor(id: number) { this._members = this._members.filter((m) => m !== id); }
  }
  class Game_Player {
    x = 3;
    y = 4;
    speed = 4;
    through = false;
    transfer: unknown = null;
    canEncounter() { return true; }
    performTransfer() {}
    reserveTransfer(map: number, x: number, y: number) { this.transfer = { map, x, y }; }
    setMoveSpeed(n: number) { this.speed = n; }
    moveSpeed() { return this.speed; }
    setThrough(t: boolean) { this.through = t; }
    isThrough() { return this.through; }
  }
  const flags = (): { d: Record<number, unknown>; value(i: number): unknown; setValue(i: number, v: unknown): void } => ({
    d: {},
    value(i) { return this.d[i] ?? 0; },
    setValue(i, v) { this.d[i] = v; },
  });
  const sandbox: Record<string, any> = {
    WebSocket,
    setTimeout,
    clearTimeout,
    console,
    PluginManager: { parameters: (name: string) => (name === "TelosBridge" ? { HubUrl: hubUrl } : {}) },
    Game_Actor,
    Game_Party,
    Game_Player,
    BattleManager: { processVictory() {}, processDefeat() {}, startBattle() {} },
    $dataSystem: { gameTitle: "Hero Quest", currencyUnit: "G", switches: ["", "Door open", "Boss beaten"], variables: ["", "Quest step", "Coins found"] },
    $dataItems: [null, { id: 1, name: "Potion", price: 50, description: "Heals 50 HP" }, { id: 2, name: "Hi-Potion", price: 200, description: "Heals 200 HP" }],
    $dataWeapons: [null, { id: 1, name: "Bronze Sword", price: 100, description: "" }],
    $dataArmors: [null, { id: 1, name: "Leather Cap", price: 40, description: "" }],
    $dataActors: [null, { id: 1, name: "Harold" }, { id: 2, name: "Therese" }, { id: 3, name: "Marsha" }],
    $dataMapInfos: [null, { id: 1, name: "Town" }, { id: 2, name: "Dark Cave" }],
    $dataCommonEvents: [null, { id: 1, name: "Inn rest" }],
    $gameParty: null as unknown,
    $gamePlayer: null as unknown,
    $gameMap: { mapId: () => 1, displayName: () => "Town" },
    $gameActors: { actor: (id: number) => actors[id] },
    $gameSwitches: flags(),
    $gameVariables: flags(),
    $gameTemp: { reserved: 0, reserveCommonEvent(id: number) { this.reserved = id; } },
    $gameSystem: { playtimeText: () => "01:02:03" },
    actors,
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  // As in the game: the plugin loads (and hooks the classes) before a save is started.
  vm.runInContext(fs.readFileSync(PLUGIN, "utf8"), sandbox, { filename: "TelosBridge.js" });
  sandbox.$gameParty = new sandbox.Game_Party();
  sandbox.$gamePlayer = new sandbox.Game_Player();
  return sandbox;
}

async function call(tool: string, input: Record<string, unknown> = {}) {
  const out = await hub.adapters.callTool("rpgmaker", tool, input);
  return JSON.parse(typeof out === "string" ? out : JSON.stringify(out));
}

before(async () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "telos-rpgm-hub-"));
  hub = await createHub({
    root,
    port: 0,
    lan: false,
    token: "t",
    dataDir,
    brain: { model: "test", createStream: fakeModel(() => ({ content: [text("ok")] })).factory },
    jev: null,
  });
  const port = (hub.server.address() as AddressInfo).port;
  game = rpgMakerRuntime(`ws://127.0.0.1:${port}/ws/adapter`);
  for (let i = 0; i < 100 && !hub.adapters.find("rpgmaker"); i++) await new Promise((r) => setTimeout(r, 50));
});

after(() => {
  game?.TelosBridge?.stop();
  hub?.close();
});

test("the plugin connects as the 'rpgmaker' adapter, named after the game", () => {
  const a = hub.adapters.state().find((x) => x.prefix === "rpgmaker");
  assert.ok(a, "connected");
  assert.equal(a!.name, "RPG Maker bridge: Hero Quest");
  for (const t of ["status", "read", "gold", "items", "give", "actor", "heal_party", "party", "switch", "variable", "teleport", "player", "common_event"]) {
    assert.ok(a!.tools.includes(t), t);
  }
});

test("status, gold and items", async () => {
  const s = await call("status");
  assert.equal(s.gold, 300);
  assert.deepEqual(s.party.map((m: { name: string }) => m.name), ["Harold", "Therese"]);
  assert.deepEqual(s.map, { id: 1, name: "Town", x: 3, y: 4 });

  assert.deepEqual(await call("gold", { add: 700 }), { before: 300, after: 1000, max: 99999999 });
  assert.equal((await call("gold", { set: 5 })).after, 5);
  assert.deepEqual(await call("read", { what: "gold" }), { value: 5 });

  const found = await call("items", { query: "potion" });
  assert.deepEqual(found.map((i: { name: string }) => i.name), ["Potion", "Hi-Potion"]);
  assert.deepEqual(await call("give", { item: "hi-potion", count: 5 }), { item: "Hi-Potion", before: 0, after: 5, max: 99 });
  assert.equal((await call("give", { item: "Bronze Sword", kind: "weapon" })).after, 1);
  assert.deepEqual(await call("read", { what: "item", id: 2 }), { value: 5 });
});

test("party members: stats, levels, healing, joining", async () => {
  const r = await call("actor", { actor: "therese", level: 20, add_param: { atk: 15, mhp: 30 }, hp: 999 });
  assert.equal(r.after.level, 20);
  assert.equal(r.after.mhp, 150);
  assert.equal(r.after.hp, 150, "HP is capped at the new max");
  assert.equal(game.actors[2].atk, 25);
  game.actors[1].hp = 3;
  await call("heal_party");
  assert.equal(game.actors[1].hp, 120);
  assert.deepEqual((await call("party", { add: "Marsha" })).party, ["Harold", "Therese", "Marsha"]);
});

test("switches and variables by the developer's names, teleporting, walking", async () => {
  assert.deepEqual(await call("switch", { id: "boss", value: true }), { id: 2, name: "Boss beaten", before: 0, after: true });
  assert.deepEqual(await call("variable", { id: "coins", add: 7 }), { id: 2, name: "Coins found", before: 0, after: 7 });
  assert.deepEqual((await call("variable", { query: "quest" }))[0], { id: 1, name: "Quest step", value: 0 });

  await call("teleport", { map: "dark cave", x: 10, y: 12 });
  assert.deepEqual(game.$gamePlayer.transfer, { map: 2, x: 10, y: 12 });

  const p = await call("player", { speed: 9, through_walls: true, encounters: false });
  assert.deepEqual(p, { speed: 6, through_walls: true, encounters: false });
  assert.equal(game.$gamePlayer.canEncounter(), false, "the hook turns random encounters off");
  await call("player", { encounters: true });
  assert.equal(game.$gamePlayer.canEncounter(), true);

  assert.deepEqual(await call("common_event", { id: "inn" }), { running: "Inn rest" });
  assert.equal(game.$gameTemp.reserved, 1);
});

test("mistakes come back as helpful errors", async () => {
  await assert.rejects(call("give", { item: "pot" }), /Several items match "pot": Potion \(1\), Hi-Potion \(2\)/);
  assert.equal((await call("give", { item: "potion", count: 0 })).item, "Potion", "an exact name wins over partial ones");
  await assert.rejects(call("actor", { actor: "Zed" }), /No actor called "Zed"/);
  await assert.rejects(call("actor", { add_param: { charisma: 5 } }), /Unknown stat "charisma"/);
  await assert.rejects(call("switch", { id: 40 }), /No switch 40 \(there are 2\)/);
  const map = game.$gameMap;
  game.$gameMap = { mapId: () => 0, displayName: () => "" }; // the title screen
  await assert.rejects(call("status"), /No game is loaded yet/);
  game.$gameMap = map;
});

test("game events reach Telos (and game links): gold changes, map changes", async () => {
  const seen: string[] = [];
  const onEvent = (e: { text: string }) => seen.push(e.text);
  hub.adapters.on("event", onEvent);
  game.$gameParty.gainGold(10);
  game.$gamePlayer.performTransfer();
  for (let i = 0; i < 50 && seen.length < 2; i++) await new Promise((r) => setTimeout(r, 20));
  hub.adapters.off("event", onEvent);
  assert.deepEqual(seen, [`Gold is now ${game.$gameParty.gold()}`, "Map changed: Town"]);
});
